# Generated by Django 5.2.12 on 2026-03-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bpm', models.IntegerField()),
                ('key', models.CharField(max_length=20)),
                ('duration', models.FloatField()),
                ('genre', models.CharField(choices=[('lofi', 'Lofi'), ('ambient', 'Ambient'), ('synthwave', 'Synthwave'), ('nature', 'Nature/Textures')], max_length=50)),
                ('loop_type', models.CharField(choices=[('beat', 'Beat / Rhythm'), ('bass', 'Bassline'), ('chord', 'Chords / Pad'), ('melody', 'Melodic Lead'), ('texture', 'Atmospheric Texture'), ('vocal', 'Vocal/Chop')], default='beat', max_length=20)),
                ('audio_file', models.FileField(upload_to='loops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
